### ISSUE TITLE
Feature: Allow users to submit lyrics to songs with no lyrics found

### ISSUE THREAD

**Issue by omarabdelaz1z** [KL13NT/valbot#186]
-lyrics
possible options: -a -u

-a for add
-u for update

**Comment by KL13NT** [comment]
Things to think about:
- Adding a voting system for lyrics before considering them sound
- Report option for misleading lyrics submitted by other users
- Disclaimer what the source for said lyrics is
- Prompt for when lyrics are not found
- Handling for files when lyrics are too large (I see you, Eminem!)

**Comment by KL13NT** [comment]
Closing as too broad for the scope of this project.
