### ISSUE TITLE
Feature: Ignore NSFW channels from toxicity filtering

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#19]
Currently the bot flags NSFW/toxic messages using the `ToxicityController` module even when a message is sent in a NSFW channel. This should be changed for a more friendly interface.

## Related LOC
The `MessageListener` module uses this function, `shouldHandle` to determine whether it should handle a message. Add a condition to use the `nsfw` [flag](https://discord.js.org/#/docs/main/12.5.3/class/TextChannel?scrollTo=nsfw) on the `channel` object.
https://github.com/KL13NT/valbot/blob/ccc0c43ab15490f0c94cf6f97b9db72679c50147/src/listeners/MessageListener.ts#L55-L70

**Comment by Amrsamy19** [comment]
Can I be assigned to this issue?

**Comment by KL13NT** [comment]
Implemented in #80
