### ISSUE TITLE
Integrated Music Player

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#20]
This issue discussed the addition of music playing. It should support the following commands in the initial release:
- [x] `play`: play youtube links
- [x] `pause`: pauses currently playing song, keeps queue
- [ ] `play`: to resume paused songs
- [x] `skip`: skips current song, keeps queue
- [x] `clear`: stop currently playing, clears queue
- [x] `list`: lists current queue
- [x] `np`: now playing
- [ ] `loop`: toggles looping mode

Later on we could add:
- `play`: youtube playlists
- `play`: support for spotify songs and playlists
- `seek`
- `move`
- `lyrics`
- `prev`
- `disconnect`
- `save`: save current queue as a playlist

Possibly:
- `shuffle`

Conditions:
- If requesting user is not in voice channel, reply `bad`
- If requesting user is in voice channel but deafened, reply `bad`
- If requesting user is in voice channel and no deafened, join and play
- If song cannot be played, reply with reason
- If all users in voice channel disconnect, timeout 1 minute later
- If all users in voice channel are deafened for 1 minute, disconnect

**Comment by omarabdelaz1z** [comment]
- command ```play``` should accept multiple URLs. 
```text
play URL(1) URL(2) ... URL(n) 
```

**Comment by KL13NT** [comment]
Work on the pause feature, now

![](https://cdn.discordapp.com/attachments/571824874969104416/888568860440150046/154676083_2923698614569040_2314181195288934580_n.jpg)

**Comment by omarabdelaz1z** [comment]
Two features done
![image](https://user-images.githubusercontent.com/59033999/133898257-7b02c57a-3c37-478b-8e8b-a91a46f3ff4d.png)
