### ISSUE TITLE
Feature: Remove track from queue (by id)

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#65]
A remove command for the music controller. It should be called by `-remove 5` for example. Accepts one parameter that must be a number. Should be `-1` to accommodate for `-queue`'s `+1`. Check other music commands such as `skip` or `play` for the other conditions. You'll probably need to  add a method for this on the `MusicController` controller.

**Comment by 1Kuroyasha** [comment]
Can I get assigned to this ?
