### ISSUE TITLE
Feature: Move song to different position in queue

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#77]
This should be fairly straight-forward if you've been digging in the code. The goal is for a user to be able to `move 4 5` to swap the song in position `4`  to position `5`. The format is `<from> <to>`.

## Conditions
- If the `from` position is the position of the currently playing song, reply with `You can't move the currently playing song` and return

## Related LOC
Check other commands such as `play` for the validation conditions. The command should be called `move` and have a `m` alias. It should accept two parameters, no optional parameters, and no extra parameters.

**Comment by 1Kuroyasha** [comment]
What do you think about making the <to> parameter an optional one, and if passed the first parameter only move the song to the next position and shift the rest of the queue. I personally think it would be a great addition to the command. And I was hoping that you would assign me to this issue.

**Comment by omarabdelaz1z** [comment]
> What do you think about making the second parameter an optional one, and if passed the first parameter only move the song to the next position and shift the rest of the queue. I personally think it would be a great addition to the command. And I was hoping that you would assign me to this issue.

This is a good idea. I'd like to see it.
