### ISSUE TITLE
Feature: previousNow music command

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#78]
The bot will support jumping to a song position soon, but will have no way of going back directly to avoid remembering the index. Add the handling for a `previousNow` command that directly plays the previous song. It should use the existing `jump` logic on the `MusicController`. It should have `prevNow` and `prev` as aliases. 

## Related LOC
A new command should be added that uses the `jump` method of the `MusicController` with argument `-1`: 
https://github.com/KL13NT/valbot/blob/9086758172c686ecaf18eb43ea99abc6af39f8ac/src/controllers/MusicController.ts#L221

**Comment by 1Kuroyasha** [comment]
Can you assign me to this ?

**Comment by KL13NT** [comment]
There you go ![](https://c.tenor.com/omJbisofB98AAAAC/pepe-clown.gif)

**Comment by 1Kuroyasha** [comment]
Thank you sir. I respectfully inform you that I really appreciate your work it truly is a piece of art.
