### ISSUE TITLE
Refactor: Jump command should have shorter cooldown

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#81]
Modify the related line to be `5` seconds instead of `15`. 

## Related LOC
https://github.com/KL13NT/valbot/blob/9086758172c686ecaf18eb43ea99abc6af39f8ac/src/commands/jump.ts#L12

**Comment by durgeshahire07** [comment]
can u assign this to me?

**Comment by KL13NT** [comment]
Absolutely! :)

**Comment by omarabdelaz1z** [comment]
Any updates? @durgeshahire07

**Comment by durgeshahire07** [comment]
Hey, sorry for being late. 
I have created the PR, you can review it
