### ISSUE TITLE
Bug: music player presence is not cleared after stopping

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#89]
**Describe the bug**
The bot's status remains on the last song played even when the queue is cleared and the bot disconnected.

**To Reproduce**

1. Play any song using `-p`
2. Wait for the song to play and the bot's status to change
3. Disconnect it/use `-stop` or `-cq`
4. Watch the status not clear

**Expected behavior**
The bot's status should be cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/20807178/135725183-878270ca-0c3a-48ea-9601-e3780b274185.png)

**Additional context**

**Comment by KL13NT** [comment]
A possible fix would be to clear the presence in the `MusicController` in `#disconnect`.

**Comment by 1Kuroyasha** [comment]
Can I get assigned to this please ?

**Comment by KL13NT** [comment]
Welcome on board! 😀
