### ISSUE TITLE
Bug: command uppercase sensitivity incompatibility

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#90]
**Describe the bug**
When running commands with uppercase letters such as `previousNow` the command isn't launched, despite a complete match between the command's name and the user written command.

**To Reproduce**
Use the `previousNow` alias of the `prev` command. The command won't run. 

**Expected behavior**
Aliases and command names that have different cases should run regardless the user wrote them correctly.

**Additional context**
The bug occurs because the `CommandsLoader` doesn't lowercase command names nor aliases while the `CommandListener` tries to match the input by lowercasing first. A fix may be implemented by mapping the command to its lower-case counterpart, while keeping the name and the list of aliases on the object for use with `help` command.

**Comment by skawy** [comment]
Can I be assigned to this  👉😳👈

**Comment by KL13NT** [comment]
مش هديهالك الا لما تشيل الوش

**Comment by skawy** [comment]
done captain nabil

**Comment by KL13NT** [comment]
![](https://c.tenor.com/KMxrZ-A6ev4AAAAM/nice-smack.gif)

**Comment by skawy** [comment]
https://tenor.com/yfr8.gif

**Comment by skawy** [comment]
![image](https://user-images.githubusercontent.com/63661486/135738419-3f854cf7-afb0-44fb-87f9-aded256f3f97.png)
