### ISSUE TITLE
Bug: bot dies after skipping when paused

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/valbot#92]
**Describe the bug**
When the bot is paused and `skip` is called it doesn't 

**To Reproduce**

1. play link
2. play another link
3. pause
4. skip
5. play (continue)
6. watch as the world burns

**Expected behaviour**
It should continue normally, but doesn't at all no matter what we do.

**Comment by skawy** [comment]
اكتب حاجه عشان يعملى اساين

**Comment by KL13NT** [comment]
The bug seems to be that `skip` doesn't respect `pause` and that `play`  command when resuming doesn't handle resuming correctly. A modification to `skip` to force it to reset `position` to `null` when moving and to `play` when paused OR playing would fix part of it. Modifying the play command to check whether there's a position stored and the state is `paused` would fix it as well.

**Comment by KL13NT** [comment]
Fixed in #4148717
